name: Taskflow Entire CI/CD Pipeline

on: 
  push:
    branches: [production]
  pull_request: 
    branches: [production]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [shell, mfe-task, mfe-board]

    steps:
      - name: Greeting to Linting step
        run: echo "Welcome to Lint Check step"

      - name: Extract Folders and files
        uses: actions/checkout@v4

      - name: Setting up the Node JS Environment
        uses: actions/setup-node@v4
        with: 
          node-version: "24"
          cache: "npm"

      - name: Installing Dependencies
        working-directory: ${{matrix.project}}
        run: npm install
      
      - name: Checking Linting errors
        working-directory: ${{matrix.project}}
        run: npm run lint

  build-check:
    runs-on: ubuntu-latest
    needs: lint-check
    strategy:
      fail-fast: false
      matrix:
        project: [shell, mfe-task, mfe-board]

    steps:
      - name: Greeting to Building Check step
        run: echo "Welcome to Build Check step"

      - name: Extract Folders and files
        uses: actions/checkout@v4

      - name: Setting up the Node JS Environment
        uses: actions/setup-node@v4
        with: 
          node-version: "24"
          cache: "npm"

      - name: Installing Dependencies
        working-directory: ${{matrix.project}}
        run: npm install
      
      - name: Checking Linting errors
        working-directory: ${{matrix.project}}
        run: npm run build

  initialize-deploy:
    runs-on: ubuntu-latest
    needs: build-check
    if: github.ref == 'refs/heads/production'
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: shell
            project_id_secret: VERCEL_PROJECT_ID_SHELL
          - project: mfe-task
            project_id_secret: VERCEL_PROJECT_ID_MFE_TASK
          - project: mfe-board
            project_id_secret: VERCEL_PROJECT_ID_MFE_BOARD
    steps:
      - name: "Pull codes from Repo"
        uses: actions/checkout@v4

      - name: "Installing Vercel CLI"
        run: npm install --global vercel@latest

      - name: "Pull Vercel Environment"
        working-directory: ${{ matrix.project }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets[matrix.project_id_secret] }}

      - name: "Build Vercel Environment"
        working-directory: ${{ matrix.project }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets[matrix.project_id_secret] }}

      - name: "Deploy In Vercel environment"
        working-directory: ${{ matrix.project }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets[matrix.project_id_secret] }}
